[package]
name = "numbercrunching"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0"
itertools = "0.10.3"
float-cmp = "0.9.0"
